---

- hosts: all

  become: true
  become_user: root
  become_method: sudo

  roles:
    - ansible-role-openssl-selfsigned-cert
    - ansible-role-apache
    - postgresql
    # - mysql
    - ansible-role-openjdk-jdk
    - ansible-role-nodejs
    - liferay
    - notification-service
